#!/usr/bin/env bash
# bash script that displays To infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
while true
do
	trap "echo 'I am invincible'" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
