#!/usr/bin/env bash
# bash script that displays To infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
trap "echo ""I"" ""a""m"" ""i""n""v""i""n""c""i""b""l""e""" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
