#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
N=$(ls -1)
for i in $N; do echo "$i" | cut -d '-' -f2; done
